{"Launchpad":"https://bugs.launchpad.net/bugs/1391311","Id":"1391311","Gerrit":"https://review.openstack.org/#/c/138526/","IdGerrit":"","IdCommit":"46fdb37c68b605d26f98ac673ebe4e70c39b4b99","Files":["cinder/tests/unit/test_huawei_drivers.py","cinder/volume/drivers/huawei/huawei_driver.py","cinder/volume/drivers/huawei/huawei_utils.py"],"Lines_Inseted":21,"Lines_Deleted":4,"CommitParent":"78cd21b1c9c429792024596f608c6a6d5d583fa2","Classification":"Bug","KeywordsTitle":"vulnerable","Description":"is not doing,passed, ","KeywordsCommit":"fix, Modify, to use.","Comments":"the review is  https://review.openstack.org/133831, It's a bug report because the service is not passing the kwargs"}