{"Launchpad":"https://bugs.launchpad.net/bugs/1307791","Id":"1307791","Gerrit":"https://review.openstack.org/89298","IdGerrit":"89298","IdCommit":"54f4600c82241ad6ae6768d3dcd1e1755dac4ddc","Files":["nova/compute/api.py","nova/tests/unit/compute/test_compute_api.py"],"Lines_Inseted":40,"Lines_Deleted":18,"CommitParent":"c1add5d245ce493c475c5084def0b59d748d1056","Classification":"Bug","KeywordsTitle":"Volumes still in use after deleting ","Description":"volumes are still in state of \"in-use\" after deleting","KeywordsCommit":" patch use local deleting to cleanup ","Comments":"Malfunctioning "}