{"Launchpad":"https://bugs.launchpad.net/bugs/1336127","Id":"1336127","Gerrit":"https://review.openstack.org/106477","IdGerrit":"106477","IdCommit":"6ddd9f93f82427ce909c7773f7a806361035a0b2","Files":["nova/compute/manager.py","nova/tests/compute/test_compute_mgr.py"],"Lines_Inseted":4,"Lines_Deleted":14,"CommitParent":"70feb102ae86d3421e46a07710e4cbab35408d02","Classification":"Bug","KeywordsTitle":"rescheduling fails,  virtual machine fails ","Description":"if virtual machine fails to be created rescheduling fails.","KeywordsCommit":"volume cleanup has been moved to take place when a build is aborted","Comments":"."}