{"Launchpad":"https://bugs.launchpad.net/bugs/1410622","Id":"1410622","Gerrit":"https://review.openstack.org/156579","IdCommit":"ca3862cd2a8086fff712efe79e0bf013eda33505","Files":["nova/tests/unit/test_utils.py","nova/tests/unit/virt/libvirt/test_utils.py","nova/utils.py","nova/virt/libvirt/utils.py"],"Lines_Inseted":16,"Lines_Deleted":1,"CommitParent":"43078b5f7f8af8f7392e648b6c7524b77a68e27b","Classification":"Bug","KeywordsTitle":"broken","Description":"bug, fixed, issue,failures , trying, ","KeywordsCommit":"","Comments":"It's a bug report, the related fix is at https://review.openstack.org/#/c/152112/, "}