{"Launchpad":"https://bugs.launchpad.net/bugs/1360252","Id":"1360252","Gerrit":"https://review.openstack.org/147999","Files":["neutron/tests/functional/db/test_sqla_utils.py"],"Lines_Inseted":0,"Lines_Deleted":0,"CommitParent":"b3db517a521cf1d4f2854101204702efda66ad9d","Classification":"Not_Bug","KeywordsTitle":"testtools breaks ","Description":"tests fails","KeywordsCommit":"","Comments":"can not retreive commit from neutron repo. "}