{"Launchpad":"https://bugs.launchpad.net/bugs/1488730","Id":"1488730","Gerrit":"https://review.openstack.org/#/c/200293","IdGerrit":"200293","IdCommit":"fe236bdaadb949661a0bfb9b62ddbe432b4cf5f1","Files":["neutron/agent/l3/dvr_edge_router.py","neutron/agent/l3/dvr_local_router.py","neutron/agent/l3/router_info.py"],"Lines_Inseted":4,"Lines_Deleted":4,"CommitParent":"656721987b0f62de2e31782ca03611ae5afa7cd8","Classification":"Bug","KeywordsTitle":"set, is not recoverd,","Description":"small bug, is not recovered, detail operations, make sure, should be successful,","KeywordsCommit":"Remove, doesn't need, ","Comments":"It's a bug report. But in the description of then commit we cannot find the 'closes-bug' as in SZZ algorithm"}